### ISSUE TITLE
Failed to log into steam

### ISSUE THREAD

**Issue by asdfmonster261** [kurokobo/game-update-notifier#16]
Starting today I am getting this error in the logs. I've tried using it on two different networks and three machines with the same results. I am able to log into steamcmd anonymously on all machines.

```[__main__] INFO: Loop start: 2024-10-10 22:39:30.243002
[modules.steam] INFO: Log in to Steam
[modules.steam] INFO: Invoke anonymous login
[modules.steam] ERROR: Failed to log in to Steam
[modules.steam] ERROR: Failed to log in to Steam
[modules.steam] INFO: Log out from Steam
[__main__] INFO: Will sleep 300 seconds

**Comment by kurokobo** [comment]
Thanks for the report, will test on my side.

**Comment by kurokobo** [comment]
https://github.com/ValvePython/steam/issues/474

**Comment by denizkoekden** [comment]
I dont know if this gets fixes ASAP because the Maintainers of the ValvePython/steam Project didn't do anything since 2 years. You can implement the wsproto-Branch from njbooher (https://github.com/njbooher/steam/tree/wsproto) and then add the following to the Project:

to requirements.txt add:

```
https://github.com/njbooher/steam/archive/wsproto.zip

wsproto
```

and then in helper/app_finder.py:

`from steam.core.connection import WebsocketConnection` as import here 

https://github.com/kurokobo/game-update-notifier/blob/c8117773c5a27e051c45bbc6132e878ffca41f4d/helper/app_finder.py#L10

 and then after here https://github.com/kurokobo/game-update-notifier/blob/c8117773c5a27e051c45bbc6132e878ffca41f4d/helper/app_finder.py#L19 put

`_client.connection = WebsocketConnection()`

and it should work again as it is now using WebSocket instead of TCP for connecting to Steam.

**Comment by kurokobo** [comment]
@denizkoekden 
Thanks, I already saw your comments on the issue and the related PR to support WS, and I also saw that the maintainer has been inactive lately😢 I'm going to take a quick look and see whether I should use the PR branch directly.

**Comment by denizkoekden** [comment]
The root of the problem is that the Steam Connection Manager is flaky (https://steamstat.us/) and I guess they prefer Websocket over TCP for now. My "solution" is only meant to fix it temporarly and I hope one of the maintainers will implement Websockets ASAP. I mentioned the most active maintainer in the PR.

**Comment by kurokobo** [comment]
It seems that the issue on Steam's side has been resolved, as the code that stopped working few weeks ago is now functioning again 🤔

That said, the dependencies have become outdated, so I think I will just update them.
